### ISSUE TITLE
El parseo bloque Driver Activity no es correcta

### ISSUE THREAD

**Issue by masalinas** [Negrero/tachograph-card-structure#1]
He estado parseando algunos ficheros TGD de tarjetas de conductores y me he fijado que el parseo para calcular el bloque de Driver Activity, lo hace erroneamente:

fileBlockTGD.getDriver_activity_data().getActivityDailyRecords() solo devuelve un solo registro siempre con fecha Thu Jan 01 01:00:22 CET 1970 y en la misma agrupa toda la colección ActivityChangeInfo, he visto también que no coinciden todos los registros ActivityChangeInfo con los que existen en realidad. 

Estoy usando readesm para comparar lo que lee la herramienta con lo que lee tus fuentes.

Sabes si está corregido?, estoy en lo cierto?

Si quieres más detalles tengo el TGD de ejemplo que estoy usando.

Gracias ...

**Comment by valdepeace** [comment]
.
Lo de la clase ActivityChangeInfo  he estado mirando lo que falta son registros, que  segun los ficheros que yo tengo de conductor, lo miro y corrijo en estos días es problema de indice de la secuencia ciclica de registros. Tambien creo recordar que hay una revision que no se si afecta ha esta clase ya que los ficheros que estoy utilizando son del 2007 y de un solo conductor. Puede tb que este el archivo corrupto ya que cuando la secuencia de bytes a leer no es correcta da la fecha que utilizada es el numero de segundos a partir de 1 de enero de 1970, pero si con readesm los lee tiene que estar bien.

Te agradeceria que me enviaras los archivos para poder analizarlos a mi correo valdepeace@gmail.com, y de esa manera poder analizar distintos archivos y poder testear a fondo las librerias, agradezco el interes puesto.

Un saludo

**Comment by masalinas** [comment]
Ok, perfecto y gracias, te adjunto el fichero TGD (Tarjeta de conductor) con el que he probado y he leído con readesm.

![c_e09355108l000000_e_20130626_1028](https://cloud.githubusercontent.com/assets/1216181/8226025/5806acb2-159b-11e5-9e4c-cf6316f1d3c6.jpg)

Tuve que renombrar el fichero a JPG, pero realmente es un fichero TGD, le vuelves a cambiar la extensión y está. Sino puedes descargarlo te lo paso por correo.

Gracias.

**Comment by masalinas** [comment]
Buen trabajo, ok, perfecto, te adjunto el fichero pero lo tuve que renombrar a JPG porque no me deja github guardar ficheros diferentes, le vuelves a colocar la extensión a TGD y listo

![c_e09355108l000000_e_20130626_1028](https://cloud.githubusercontent.com/assets/1216181/8226343/44755164-159e-11e5-8cc4-39090286529b.jpg)

Muchas gracias, esperamos con ganas esa corrección.

**Comment by valdepeace** [comment]
Corregido el fallo, era problema que en cardDriverActivity en el array de bytes habia que quitarle los 4 primeros bytes del array, dos bytes es para activityPointerOldestDayRecord y los otros dos para activityPointerNewestRecord.

![portapapeles02](https://cloud.githubusercontent.com/assets/3323178/8243789/820cd408-161a-11e5-8755-78c3cc19c362.png)

Gracias y agradeceria si vieras algun fallo mas me lo comentaras o algo que mejorar, este verano me quiero liar con los de la unidad intravehicular y el resto de tarjetas.

**Comment by masalinas** [comment]
Fantástico, voy a bajarme los cambios. Otra pregunta los ficheros TGD de tacógrafo tienen una estructura de bloques diferentes a los TGD de conductor?, tu librería es capaz de leerlos?

Gracias

**Comment by valdepeace** [comment]
A la primera pregunta si (mirate boe num 105 3 mayo de 2005 pagina 15127). La forma en que se graba los bytes es diferente a los de las tarjetas, aunque el desarrollo de las clases y lectura de fichero es la misma que para los de las tarjetas, solo se aprobecharia algunas clases de los subbloques ya que son datos iguales tanto para la tarjeta como para la vu.                                                                                                                                                                                    

A la segunda pregunta no, solo son para ficheros de tarjetas. 

Es lo que quiero hacer este verano desarrollar las 5 clases que me faltan de las tarjetas de empresa, control y ensayo(que puedes ver en el cuadro resumen) y despues los de la vu que son sobre 150 clases, dependerá del tiempo que le pueda dedicar.

**Comment by masalinas** [comment]
El cambio funciona correctamente, una pregunta veo que para calcular el estado de la actividad del conductor se utiliza dos bits, por lo tanto cuatro estados: PAUSA/DESCANSO, DISPONIBILIDAD, TRABAJO y CONDUCCIÓN, la pregunta es: ¿Que condición se debe de cumplir para que el estado sea UNKNOWN o SHORT BREAK (los pongo en ingles sacados del readesm), o lo que es lo mismo como soy capaz de inferir estos dos estados?

Gracias

**Comment by valdepeace** [comment]
Codigo readesm:

---

void ActivityChangeInfo::setDuration(int newDuration, bool newIsSlotState){
    duration = newDuration;
    isSlotState = newIsSlotState;
    if(a == 0 && duration < 15) activity = SHORTREST;
    if(!isSlotState && (p != 0) && (c == 0)) activity = UNKNOWN;
}

QString ActivityChangeInfo::activityName() const {
    switch(activity){
        case REST: return tr("break/rest");
        case AVAILABLE: return tr("availability");
        case WORK: return tr("work");
        case DRIVING: return tr("driving");
        case UNKNOWN: return tr("unknown");
        case SHORTREST: return tr("short break");
    }
    return tr("unknown activity");
}

---

Analizando el codigo en la linea "if(a == 0 && duration < 15) activity = SHORTREST":
Como veras todo tiempo menor de 15 minutos lo toma como pequeño descanso donde aa ==0 es descanso/pausa.

Analizando el codigo en la linea "if(!isSlotState && (p != 0) && (c == 0)) activity = UNKNOWN;":
Si p no es igual a 0 y c es igual a 0 osea que p=1 y c=0

Segun la normativa p y c:

---

′p′B Estado de la tarjeta:
                ′0′B: INSERTADA, la tarjeta está insertada en un equipo de control,
                ′1′B: NO INSERTADA, la tarjeta no está insertada (o se ha extraído),
 ′c′B  Régimen de conducción (caso ′p′ = 0): 
                 ′0′B: EN SOLITARIO, 
                 ′1′B: EN EQUIPO,
 Régimen en la actividad siguiente (caso ′p′ = 1): 
                  ′0′B: INDETERMINADO 
                  ′1′B: DETERMINADO (= entrada manual)

---

Segun la normativa:

---

 Nota sobre el caso «extracción de la tarjeta»:

 Cuando se extrae la tarjeta:
        — ′s′ es relevante e indica la ranura de la que se extrae la tarjeta,
        — ′c′ debe configurarse a 0,
        — ′p′ debe configurarse a 1,
        — ′aa′ debe codificar la actividad que esté seleccionada en ese momento,

 Como resultado de una entrada manual, los bits ′c′ y ′aa′ de la palabra (almacenada en una tarjeta) se pueden sobrescribir posteriormente para reflejar la entrada.

---

Por lo que la actividad de unknown creo que corresponde a tarjeta extraida.

Ten en cuenta que esta clase controla la actividad de 24 horas por lo que comienza a las 00:00 y termina a las 24:00 por lo que yo solo interpreto los bits según la normativa y no controlo la duración de cada cambio de actividad, readesm lo controla ya que muestra la gráfica y necesita la duración.

Eso lo tendre que contemplar en la gestiontgd a la hora de realizar la grafica del cambio de actividad por dia.

¿Añadirias tu tb, una prodiedad al cambio de actividad con la duracion de dicha actividad? o ¿lo dejo mejor que controle el cliente que consuma dichas librerias?

**Comment by masalinas** [comment]
Yo creo que lo tienes bien tu, y que cada uno tenga en cuenta estos cambios de actividad yo ya he añadido la lógica en mi app, tanto para los cambios de estado: unknown(desconocido) como para el estado short/break(pausa), para asemejarme a readesm.Para el estado de pausa he teniendo en cuenta la duración de los intervalos como tú me comentas anteriormente (15 minutos), y para el estado de desconocido he seguido el patrón de comportamiento de readesm.

He detectado un error en el mismo fichero de ejemplo que te he enviado, te lo comento:

El día 24/06/2013 que corresponde al tercer día de actividad de ese fichero TGD si te fijas existen para ese día 15 cambios de actividad correctamente pero los dos últimos (item 14 y 15), son erroneos:

Según Readesm:
Item      Hora  Estado
...          ...         ...
13          9:26   CONDUCCION (correcto)
14         11:00  PAUSA/DESCANSO (correcto)
15         11:08  PAUSA/DESCANSO. (correcto)

Según tu librería
Item       Hora  Estado
...          ...         ...
13          9:26   CONDUCCION (correcto)
14          0:0     PAUSA/DESCANSO (error)
15          0:0     PAUSA/DESCANSO. (error)

Es decir los dos último items los pones a 0:0 cuando presumiblemente deberían de ser, 11:00 y 11:08 respectivamente

Nota: el fichero para probar esto es el que te enviado, si lo necesitas de nuevo dímelo y te lo hago llegar. 

Gracias y un saludo.

**Comment by valdepeace** [comment]
Tienes razon al corregir el indice para quitarle los 4 bytes (this.activityPointerNewestRecord,this.activityPointerOldestDayRecord) de los indices donde comienza y termina el array de byte para activitychangeinfo, al desplazar el indice a copiar 4 elementos me copiaba los elementos menos 4 últimos bytes, por lo que faltaba los 4 bytes del final del array, me explico:
si el array a copiar era de 148 elementos segun "this.activityPointerNewestRecord-this.activityPointerOldestDayRecord" que pasa que eso son los elementos a copiar 148 pero al poner el indice this.activityPointerOldestDayRecord+4 ya no copiaba 148 sino 144 ya que comenzaba en el elemento 5 hasta el 148 pero en realidad lo que habia que copiar son 148 elementos osea 148+4=152, por lo que al corregir lo del indice para descartar los 4 bytes de this.activityPointerNewestRecord y this.activityPointerOldestDayRecord desplazaba los elementos a copiar asi que siempre faltarian los 4 ultimos bytes.

Por favor ¿pondrías tu  la duración de cada ActivityChangeInfo, osea una propiedad mas a dicha clase con la duración del tiempo de la actividad?

Gracias corregido y subido.

**Comment by masalinas** [comment]
Muchas gracias por la corrección, me puedes decir el fichero afectado en donde has corregido el error para ir a tiro hecho?.

Respecto a la ultima pregunta, está claro que todos los análisis relacionados con la actividad del conductor  y vehículo y por lo tanto, las incidencias que se pudieran dar, nacen de los intervalos de la actividad, por lo que la duración es vital, como te comenté  esa parte la implementé yo, para poder crear estos estadísticos. Si añades atributo a la clase ActivityChangeInfo donde reflejes esa duración de los intervalos ahorrarás bastante trabajo a quien utilice tu librería, en mi caso yo lo he hecho, pero sería una buena mejora ... ;). Si lo añades vería como modifica el código para adaptarme a este cambio.

Un saludo Miguel.

**Comment by masalinas** [comment]
He probado la corrección y funciona correctamente :)

Igualmente he intentado sacar el patrón de comportamiento del estado UNKNOWN (desconocido) comparando lo que yo saco con readesm. Mi algoritmo es:
- Si la tarjeta no está insertada ó si el Régimen en la actividad siguiente es INDETERMINADO el estado es unknown.

La verdad es que no consigo aun en reconocer este patrón de unknown, pues aveces sale como readesm y otras no, referente a este estado claro, ¿tu sabes que patrón se sigue?

Gracias  un saludo Miguel.

**Comment by masalinas** [comment]
He detectado otro error en un nuevo fichero TGD de conductor, te lo envío por correo, te puedo decir que el problema al recoger CardActivityDailyRecord en el registro del día 29 Octubre 2012, pues se pasa un array de bytes [] vacío y da un error de ArrayIndexOutOfBoundException.
